include:
  - board: dao_left//zmk
  - board: dao_right//zmk
  - board: dao_left//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: dao_left_studio
  - board: dao_right//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: dao_right_studio
  - board: nice_nano_v2
    shield: settings_reset
